# THIS CODE IS AUTOGENERATED BY src/generate_locales.py
# DO NOT EDIT THIS FILE DIRECTLY.

from locales import it, en


SUPPORTED_LANGUAGES = {'it': 'it_IT', 'en': 'en_US'}


class Translator:
    def __init__(self, locale, locale_str) -> None:
        self.locale = locale
        self.locale_str = locale_str

    def button_clan(self):
        return self.locale.BUTTON_CLAN

    def button_close(self):
        return self.locale.BUTTON_CLOSE

    def button_default_player(self):
        return self.locale.BUTTON_DEFAULT_PLAYER

    def button_general(self):
        return self.locale.BUTTON_GENERAL

    def button_issue(self):
        return self.locale.BUTTON_ISSUE

    def button_legend(self):
        return self.locale.BUTTON_LEGEND

    def button_ranked_solo(self):
        return self.locale.BUTTON_RANKED_SOLO

    def button_ranked_team(self):
        return self.locale.BUTTON_RANKED_TEAM

    def button_teammate(self):
        return self.locale.BUTTON_TEAMMATE

    def description_id(self):
        return self.locale.DESCRIPTION_ID

    def description_language(self):
        return self.locale.DESCRIPTION_LANGUAGE

    def description_legend(self):
        return self.locale.DESCRIPTION_LEGEND

    def description_me(self):
        return self.locale.DESCRIPTION_ME

    def description_search(self):
        return self.locale.DESCRIPTION_SEARCH

    def description_start(self):
        return self.locale.DESCRIPTION_START

    def error_generic(
        self,
        error
    ):
        return self.locale.ERROR_GENERIC.format(
            error=error
        )

    def error_legend_result(self):
        return self.locale.ERROR_LEGEND_RESULT

    def error_length(self):
        return self.locale.ERROR_LENGTH

    def error_missing_default_player(self):
        return self.locale.ERROR_MISSING_DEFAULT_PLAYER

    def error_no_clan_data(self):
        return self.locale.ERROR_NO_CLAN_DATA

    def error_no_ranked_data(self):
        return self.locale.ERROR_NO_RANKED_DATA

    def error_no_team_data(self):
        return self.locale.ERROR_NO_TEAM_DATA

    def error_player_not_found(
        self,
        id
    ):
        return self.locale.ERROR_PLAYER_NOT_FOUND.format(
            id=id
        )

    def error_search_result(
        self,
        query
    ):
        return self.locale.ERROR_SEARCH_RESULT.format(
            query=query
        )

    def error_team_result(self):
        return self.locale.ERROR_TEAM_RESULT

    def language(self):
        return self.locale.LANGUAGE

    def results_legends(
        self,
        current,
        total
    ):
        return self.locale.RESULTS_LEGENDS.format(
            current=current,
            total=total
        )

    def results_search(
        self,
        query,
        current,
        total
    ):
        return self.locale.RESULTS_SEARCH.format(
            query=query,
            current=current,
            total=total
        )

    def results_teams(
        self,
        current,
        total
    ):
        return self.locale.RESULTS_TEAMS.format(
            current=current,
            total=total
        )

    def search(self):
        return self.locale.SEARCH

    def stats_base(
        self,
        name,
        id
    ):
        return self.locale.STATS_BASE.format(
            name=name,
            id=id
        )

    def stats_clan(
        self,
        num,
        name,
        total,
        xp,
        current,
        id,
        date
    ):
        return self.locale.STATS_CLAN.format(
            num=num,
            name=name,
            total=total,
            xp=xp,
            current=current,
            id=id,
            date=date
        )

    def stats_general(
        self,
        games,
        hitsnowball,
        winperc,
        damagesidekick,
        xp,
        total_game_time,
        totalko,
        kosnowball,
        wins,
        loses,
        level,
        damagemine,
        kospikeball,
        totalsuicide,
        most_used_legend,
        damagebomb,
        damagespikeball,
        kosidekick,
        totaldeath,
        komine,
        kobomb,
        totalteamko,
        clan
    ):
        return self.locale.STATS_GENERAL.format(
            games=games,
            hitsnowball=hitsnowball,
            winperc=winperc,
            damagesidekick=damagesidekick,
            xp=xp,
            total_game_time=total_game_time,
            totalko=totalko,
            kosnowball=kosnowball,
            wins=wins,
            loses=loses,
            level=level,
            damagemine=damagemine,
            kospikeball=kospikeball,
            totalsuicide=totalsuicide,
            most_used_legend=most_used_legend,
            damagebomb=damagebomb,
            damagespikeball=damagespikeball,
            kosidekick=kosidekick,
            totaldeath=totaldeath,
            komine=komine,
            kobomb=kobomb,
            totalteamko=totalteamko,
            clan=clan
        )

    def stats_legend(
        self,
        games,
        koweaponone,
        koweapontwo,
        kogadgets,
        winperc,
        damageweaponone,
        xp,
        damageunarmed,
        name,
        damagegadgets,
        damagetaken,
        wins,
        loses,
        level,
        weaponone,
        teamko,
        suicide,
        id,
        weapontwo,
        damagethrownitem,
        kounarmed,
        kothrownitem,
        timeheldweaponone,
        timeheldweapontwo,
        damagedealt,
        damageweapontwo,
        matchtime,
        ko,
        death
    ):
        return self.locale.STATS_LEGEND.format(
            games=games,
            koweaponone=koweaponone,
            koweapontwo=koweapontwo,
            kogadgets=kogadgets,
            winperc=winperc,
            damageweaponone=damageweaponone,
            xp=xp,
            damageunarmed=damageunarmed,
            name=name,
            damagegadgets=damagegadgets,
            damagetaken=damagetaken,
            wins=wins,
            loses=loses,
            level=level,
            weaponone=weaponone,
            teamko=teamko,
            suicide=suicide,
            id=id,
            weapontwo=weapontwo,
            damagethrownitem=damagethrownitem,
            kounarmed=kounarmed,
            kothrownitem=kothrownitem,
            timeheldweaponone=timeheldweaponone,
            timeheldweapontwo=timeheldweapontwo,
            damagedealt=damagedealt,
            damageweapontwo=damageweapontwo,
            matchtime=matchtime,
            ko=ko,
            death=death
        )

    def stats_ranked(
        self,
        games,
        peak,
        tier,
        wins,
        glory,
        loses,
        region,
        elo_reset,
        rating
    ):
        return self.locale.STATS_RANKED.format(
            games=games,
            peak=peak,
            tier=tier,
            wins=wins,
            glory=glory,
            loses=loses,
            region=region,
            elo_reset=elo_reset,
            rating=rating
        )

    def stats_ranked_team(
        self,
        games,
        teamname,
        peak,
        tier,
        wins,
        loses,
        region,
        rating
    ):
        return self.locale.STATS_RANKED_TEAM.format(
            games=games,
            teamname=teamname,
            peak=peak,
            tier=tier,
            wins=wins,
            loses=loses,
            region=region,
            rating=rating
        )

    def status_default_player_set(self):
        return self.locale.STATUS_DEFAULT_PLAYER_SET

    def status_language_changed(self):
        return self.locale.STATUS_LANGUAGE_CHANGED

    def status_language_unchanged(self):
        return self.locale.STATUS_LANGUAGE_UNCHANGED

    def time_days(
        self,
        t
    ):
        return self.locale.TIME_DAYS.format(
            t=t
        )

    def time_hours(
        self,
        t
    ):
        return self.locale.TIME_HOURS.format(
            t=t
        )

    def time_minutes(
        self,
        t
    ):
        return self.locale.TIME_MINUTES.format(
            t=t
        )

    def time_seconds(
        self,
        t
    ):
        return self.locale.TIME_SECONDS.format(
            t=t
        )

    def usage_id(self):
        return self.locale.USAGE_ID

    def usage_search(self):
        return self.locale.USAGE_SEARCH

    def welcome(
        self,
        name
    ):
        return self.locale.WELCOME.format(
            name=name
        )


class Localization:
    def __init__(self) -> None:
        self._strings = {
            "it": Translator(it, "it_IT"),
            "en": Translator(en, "en_US"),
        }

    def get_translator(self, lang: str) -> Translator:
        if lang not in self._strings:
            raise ValueError(f"Unsupported language: {lang}")
        return self._strings[lang]
