# THIS CODE IS AUTOGENERATED BY src/generate_locales.py
# DO NOT EDIT THIS FILE DIRECTLY.

from locales import it, en


SUPPORTED_LANGUAGES = {"it": "it_IT", "en": "en_US"}


class Translator:
    def __init__(self, locale, locale_str) -> None:
        self.locale = locale
        self.locale_str = locale_str

    def button_clan(self):
        return self.locale.BUTTON_CLAN

    def button_close(self):
        return self.locale.BUTTON_CLOSE

    def button_default_player(self):
        return self.locale.BUTTON_DEFAULT_PLAYER

    def button_general(self):
        return self.locale.BUTTON_GENERAL

    def button_issue(self):
        return self.locale.BUTTON_ISSUE

    def button_legend(self):
        return self.locale.BUTTON_LEGEND

    def button_ranked_solo(self):
        return self.locale.BUTTON_RANKED_SOLO

    def button_ranked_team(self):
        return self.locale.BUTTON_RANKED_TEAM

    def button_teammate(self):
        return self.locale.BUTTON_TEAMMATE

    def description_id(self):
        return self.locale.DESCRIPTION_ID

    def description_language(self):
        return self.locale.DESCRIPTION_LANGUAGE

    def description_me(self):
        return self.locale.DESCRIPTION_ME

    def description_search(self):
        return self.locale.DESCRIPTION_SEARCH

    def description_start(self):
        return self.locale.DESCRIPTION_START

    def eerror_length(self):
        return self.locale.EERROR_LENGTH

    def error_generic(self, error):
        return self.locale.ERROR_GENERIC.format(error=error)

    def error_legend_result(self):
        return self.locale.ERROR_LEGEND_RESULT

    def error_missing_default_player(self):
        return self.locale.ERROR_MISSING_DEFAULT_PLAYER

    def error_no_clan_data(self):
        return self.locale.ERROR_NO_CLAN_DATA

    def error_no_ranked_data(self):
        return self.locale.ERROR_NO_RANKED_DATA

    def error_no_team_data(self):
        return self.locale.ERROR_NO_TEAM_DATA

    def error_player_not_found(self, id):
        return self.locale.ERROR_PLAYER_NOT_FOUND.format(id=id)

    def error_search_result(self, query):
        return self.locale.ERROR_SEARCH_RESULT.format(query=query)

    def error_team_result(self):
        return self.locale.ERROR_TEAM_RESULT

    def language(self):
        return self.locale.LANGUAGE

    def results_legends(self, current, total):
        return self.locale.RESULTS_LEGENDS.format(current=current, total=total)

    def results_search(self, current, total, query):
        return self.locale.RESULTS_SEARCH.format(
            current=current, total=total, query=query
        )

    def results_teams(self, current, total):
        return self.locale.RESULTS_TEAMS.format(current=current, total=total)

    def search(self):
        return self.locale.SEARCH

    def stats_base(self, name, id):
        return self.locale.STATS_BASE.format(name=name, id=id)

    def stats_clan(self, current, date, total, num, id, xp, name):
        return self.locale.STATS_CLAN.format(
            current=current, date=date, total=total, num=num, id=id, xp=xp, name=name
        )

    def stats_general(
        self,
        damagespikeball,
        most_used_legend,
        winperc,
        totalko,
        clan,
        totaldeath,
        kobomb,
        games,
        damagemine,
        kosidekick,
        damagebomb,
        hitsnowball,
        total_game_time,
        wins,
        kospikeball,
        damagesidekick,
        level,
        kosnowball,
        totalsuicide,
        totalteamko,
        loses,
        xp,
        komine,
    ):
        return self.locale.STATS_GENERAL.format(
            damagespikeball=damagespikeball,
            most_used_legend=most_used_legend,
            winperc=winperc,
            totalko=totalko,
            clan=clan,
            totaldeath=totaldeath,
            kobomb=kobomb,
            games=games,
            damagemine=damagemine,
            kosidekick=kosidekick,
            damagebomb=damagebomb,
            hitsnowball=hitsnowball,
            total_game_time=total_game_time,
            wins=wins,
            kospikeball=kospikeball,
            damagesidekick=damagesidekick,
            level=level,
            kosnowball=kosnowball,
            totalsuicide=totalsuicide,
            totalteamko=totalteamko,
            loses=loses,
            xp=xp,
            komine=komine,
        )

    def stats_legend(
        self,
        weapontwo,
        winperc,
        kounarmed,
        damageunarmed,
        kogadgets,
        timeheldweaponone,
        matchtime,
        death,
        games,
        id,
        damageweapontwo,
        damagethrownitem,
        timeheldweapontwo,
        weaponone,
        kothrownitem,
        suicide,
        koweaponone,
        wins,
        ko,
        name,
        koweapontwo,
        damagetaken,
        level,
        damagegadgets,
        teamko,
        damagedealt,
        loses,
        xp,
        damageweaponone,
    ):
        return self.locale.STATS_LEGEND.format(
            weapontwo=weapontwo,
            winperc=winperc,
            kounarmed=kounarmed,
            damageunarmed=damageunarmed,
            kogadgets=kogadgets,
            timeheldweaponone=timeheldweaponone,
            matchtime=matchtime,
            death=death,
            games=games,
            id=id,
            damageweapontwo=damageweapontwo,
            damagethrownitem=damagethrownitem,
            timeheldweapontwo=timeheldweapontwo,
            weaponone=weaponone,
            kothrownitem=kothrownitem,
            suicide=suicide,
            koweaponone=koweaponone,
            wins=wins,
            ko=ko,
            name=name,
            koweapontwo=koweapontwo,
            damagetaken=damagetaken,
            level=level,
            damagegadgets=damagegadgets,
            teamko=teamko,
            damagedealt=damagedealt,
            loses=loses,
            xp=xp,
            damageweaponone=damageweaponone,
        )

    def stats_ranked(
        self, rating, wins, elo_reset, games, loses, glory, tier, region, peak
    ):
        return self.locale.STATS_RANKED.format(
            rating=rating,
            wins=wins,
            elo_reset=elo_reset,
            games=games,
            loses=loses,
            glory=glory,
            tier=tier,
            region=region,
            peak=peak,
        )

    def stats_ranked_team(
        self, rating, wins, games, loses, tier, region, peak, teamname
    ):
        return self.locale.STATS_RANKED_TEAM.format(
            rating=rating,
            wins=wins,
            games=games,
            loses=loses,
            tier=tier,
            region=region,
            peak=peak,
            teamname=teamname,
        )

    def status_default_player_set(self):
        return self.locale.STATUS_DEFAULT_PLAYER_SET

    def status_language_changed(self):
        return self.locale.STATUS_LANGUAGE_CHANGED

    def status_language_unchanged(self):
        return self.locale.STATUS_LANGUAGE_UNCHANGED

    def time_days(self, t):
        return self.locale.TIME_DAYS.format(t=t)

    def time_hours(self, t):
        return self.locale.TIME_HOURS.format(t=t)

    def time_minutes(self, t):
        return self.locale.TIME_MINUTES.format(t=t)

    def time_seconds(self, t):
        return self.locale.TIME_SECONDS.format(t=t)

    def usage_id(self):
        return self.locale.USAGE_ID

    def usage_search(self):
        return self.locale.USAGE_SEARCH

    def welcome(self, name):
        return self.locale.WELCOME.format(name=name)


class Localization:
    def __init__(self) -> None:
        self._strings = {
            "it": Translator(it, "it_IT"),
            "en": Translator(en, "en_US"),
        }

    def get_translator(self, lang: str) -> Translator:
        if lang not in self._strings:
            return self._strings["en"]
        return self._strings[lang]
