# THIS CODE IS AUTOGENERATED BY src/generate_locales.py
# DO NOT EDIT THIS FILE DIRECTLY.

from locales import it, en


SUPPORTED_LANGUAGES = {'it': 'it_IT', 'en': 'en_US'}


class Translator:
    def __init__(self, locale, locale_str) -> None:
        self.locale = locale
        self.locale_str = locale_str

    def all_weapons(self):
        return self.locale.ALL_WEAPONS

    def button_clan(self):
        return self.locale.BUTTON_CLAN

    def button_close(self):
        return self.locale.BUTTON_CLOSE

    def button_default_player(self):
        return self.locale.BUTTON_DEFAULT_PLAYER

    def button_general(self):
        return self.locale.BUTTON_GENERAL

    def button_issue(self):
        return self.locale.BUTTON_ISSUE

    def button_legends(self):
        return self.locale.BUTTON_LEGENDS

    def button_ranked_solo(self):
        return self.locale.BUTTON_RANKED_SOLO

    def button_ranked_team(self):
        return self.locale.BUTTON_RANKED_TEAM

    def button_teammate(self):
        return self.locale.BUTTON_TEAMMATE

    def button_weapons(self):
        return self.locale.BUTTON_WEAPONS

    def description_id(self):
        return self.locale.DESCRIPTION_ID

    def description_language(self):
        return self.locale.DESCRIPTION_LANGUAGE

    def description_legend(self):
        return self.locale.DESCRIPTION_LEGEND

    def description_me(self):
        return self.locale.DESCRIPTION_ME

    def description_missing(self):
        return self.locale.DESCRIPTION_MISSING

    def description_search(self):
        return self.locale.DESCRIPTION_SEARCH

    def description_start(self):
        return self.locale.DESCRIPTION_START

    def description_weapons(self):
        return self.locale.DESCRIPTION_WEAPONS

    def error_generic(
        self,
        error
    ):
        return self.locale.ERROR_GENERIC.format(
            error=error
        )

    def error_legend_not_found(
        self,
        query
    ):
        return self.locale.ERROR_LEGEND_NOT_FOUND.format(
            query=query
        )

    def error_legend_result(self):
        return self.locale.ERROR_LEGEND_RESULT

    def error_length(self):
        return self.locale.ERROR_LENGTH

    def error_missing_default_player(self):
        return self.locale.ERROR_MISSING_DEFAULT_PLAYER

    def error_missing_weapons_combination_not_found(
        self,
        query
    ):
        return self.locale.ERROR_MISSING_WEAPONS_COMBINATION_NOT_FOUND.format(
            query=query
        )

    def error_no_clan_data(self):
        return self.locale.ERROR_NO_CLAN_DATA

    def error_no_ranked_data(self):
        return self.locale.ERROR_NO_RANKED_DATA

    def error_no_team_data(self):
        return self.locale.ERROR_NO_TEAM_DATA

    def error_player_not_found(
        self,
        id
    ):
        return self.locale.ERROR_PLAYER_NOT_FOUND.format(
            id=id
        )

    def error_search_result(
        self,
        query
    ):
        return self.locale.ERROR_SEARCH_RESULT.format(
            query=query
        )

    def error_team_result(self):
        return self.locale.ERROR_TEAM_RESULT

    def error_weapon_not_found(
        self,
        query
    ):
        return self.locale.ERROR_WEAPON_NOT_FOUND.format(
            query=query
        )

    def language(self):
        return self.locale.LANGUAGE

    def missing(self):
        return self.locale.MISSING

    def results_legends(
        self,
        total,
        current
    ):
        return self.locale.RESULTS_LEGENDS.format(
            total=total,
            current=current
        )

    def results_legends_with_weapon(
        self,
        weapon,
        total,
        current
    ):
        return self.locale.RESULTS_LEGENDS_WITH_WEAPON.format(
            weapon=weapon,
            total=total,
            current=current
        )

    def results_missing_weapons_combination(
        self,
        weapons
    ):
        return self.locale.RESULTS_MISSING_WEAPONS_COMBINATION.format(
            weapons=weapons
        )

    def results_missing_weapons_combination_with_weapon(
        self,
        weapons,
        weapon
    ):
        return self.locale.RESULTS_MISSING_WEAPONS_COMBINATION_WITH_WEAPON.format(
            weapons=weapons,
            weapon=weapon
        )

    def results_search(
        self,
        current,
        total,
        query
    ):
        return self.locale.RESULTS_SEARCH.format(
            current=current,
            total=total,
            query=query
        )

    def results_teams(
        self,
        total,
        current
    ):
        return self.locale.RESULTS_TEAMS.format(
            total=total,
            current=current
        )

    def search(self):
        return self.locale.SEARCH

    def stats_base(
        self,
        name,
        id
    ):
        return self.locale.STATS_BASE.format(
            name=name,
            id=id
        )

    def stats_clan(
        self,
        date,
        xp,
        num,
        current,
        id,
        total,
        name
    ):
        return self.locale.STATS_CLAN.format(
            date=date,
            xp=xp,
            num=num,
            current=current,
            id=id,
            total=total,
            name=name
        )

    def stats_general(
        self,
        hitsnowball,
        games,
        total_game_time,
        level,
        damagespikeball,
        xp,
        most_used_legend,
        wins,
        totalsuicide,
        clan,
        loses,
        totalko,
        damagemine,
        damagesidekick,
        damagebomb,
        kobomb,
        kosidekick,
        totaldeath,
        kosnowball,
        kospikeball,
        totalteamko,
        winperc,
        komine
    ):
        return self.locale.STATS_GENERAL.format(
            hitsnowball=hitsnowball,
            games=games,
            total_game_time=total_game_time,
            level=level,
            damagespikeball=damagespikeball,
            xp=xp,
            most_used_legend=most_used_legend,
            wins=wins,
            totalsuicide=totalsuicide,
            clan=clan,
            loses=loses,
            totalko=totalko,
            damagemine=damagemine,
            damagesidekick=damagesidekick,
            damagebomb=damagebomb,
            kobomb=kobomb,
            kosidekick=kosidekick,
            totaldeath=totaldeath,
            kosnowball=kosnowball,
            kospikeball=kospikeball,
            totalteamko=totalteamko,
            winperc=winperc,
            komine=komine
        )

    def stats_legend(
        self,
        bio_name,
        speed,
        defense,
        weapon_two,
        bio_aka,
        weapon_one,
        dexterity,
        strength,
        legend_id
    ):
        return self.locale.STATS_LEGEND.format(
            bio_name=bio_name,
            speed=speed,
            defense=defense,
            weapon_two=weapon_two,
            bio_aka=bio_aka,
            weapon_one=weapon_one,
            dexterity=dexterity,
            strength=strength,
            legend_id=legend_id
        )

    def stats_player_legend(
        self,
        suicide,
        kounarmed,
        timeheldweapontwo,
        damageunarmed,
        games,
        level,
        id,
        kogadgets,
        koweaponone,
        timeheldweaponone,
        matchtime,
        death,
        xp,
        name,
        wins,
        damagegadgets,
        weaponone,
        loses,
        damagethrownitem,
        damageweapontwo,
        damageweaponone,
        kothrownitem,
        damagetaken,
        koweapontwo,
        teamko,
        winperc,
        weapontwo,
        ko,
        damagedealt
    ):
        return self.locale.STATS_PLAYER_LEGEND.format(
            suicide=suicide,
            kounarmed=kounarmed,
            timeheldweapontwo=timeheldweapontwo,
            damageunarmed=damageunarmed,
            games=games,
            level=level,
            id=id,
            kogadgets=kogadgets,
            koweaponone=koweaponone,
            timeheldweaponone=timeheldweaponone,
            matchtime=matchtime,
            death=death,
            xp=xp,
            name=name,
            wins=wins,
            damagegadgets=damagegadgets,
            weaponone=weaponone,
            loses=loses,
            damagethrownitem=damagethrownitem,
            damageweapontwo=damageweapontwo,
            damageweaponone=damageweaponone,
            kothrownitem=kothrownitem,
            damagetaken=damagetaken,
            koweapontwo=koweapontwo,
            teamko=teamko,
            winperc=winperc,
            weapontwo=weapontwo,
            ko=ko,
            damagedealt=damagedealt
        )

    def stats_ranked(
        self,
        wins,
        peak,
        loses,
        games,
        glory,
        elo_reset,
        tier,
        region,
        rating
    ):
        return self.locale.STATS_RANKED.format(
            wins=wins,
            peak=peak,
            loses=loses,
            games=games,
            glory=glory,
            elo_reset=elo_reset,
            tier=tier,
            region=region,
            rating=rating
        )

    def stats_ranked_team(
        self,
        wins,
        peak,
        loses,
        games,
        tier,
        region,
        teamname,
        rating
    ):
        return self.locale.STATS_RANKED_TEAM.format(
            wins=wins,
            peak=peak,
            loses=loses,
            games=games,
            tier=tier,
            region=region,
            teamname=teamname,
            rating=rating
        )

    def status_default_player_set(self):
        return self.locale.STATUS_DEFAULT_PLAYER_SET

    def status_language_changed(self):
        return self.locale.STATUS_LANGUAGE_CHANGED

    def status_language_unchanged(self):
        return self.locale.STATUS_LANGUAGE_UNCHANGED

    def time_days(
        self,
        t
    ):
        return self.locale.TIME_DAYS.format(
            t=t
        )

    def time_hours(
        self,
        t
    ):
        return self.locale.TIME_HOURS.format(
            t=t
        )

    def time_minutes(
        self,
        t
    ):
        return self.locale.TIME_MINUTES.format(
            t=t
        )

    def time_seconds(
        self,
        t
    ):
        return self.locale.TIME_SECONDS.format(
            t=t
        )

    def usage_id(self):
        return self.locale.USAGE_ID

    def usage_search(self):
        return self.locale.USAGE_SEARCH

    def weapons(self):
        return self.locale.WEAPONS

    def welcome(
        self,
        name
    ):
        return self.locale.WELCOME.format(
            name=name
        )


class Localization:
    def __init__(self) -> None:
        self._strings = {
            "it": Translator(it, "it_IT"),
            "en": Translator(en, "en_US"),
        }

    def get_translator(self, lang: str) -> Translator:
        if lang not in self._strings:
            raise ValueError(f"Unsupported language: {lang}")
        return self._strings[lang]
